[2024-01-17 01:03:58,296] {processor.py:153} INFO - Started process (PID=171) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:03:58,297] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:03:58,298] {logging_mixin.py:115} INFO - [2024-01-17 01:03:58,298] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:03:58,320] {logging_mixin.py:115} INFO - [2024-01-17 01:03:58,319] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:03:58,321] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:03:58,343] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.067 seconds
[2024-01-17 01:04:08,403] {processor.py:153} INFO - Started process (PID=176) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:08,404] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:04:08,406] {logging_mixin.py:115} INFO - [2024-01-17 01:04:08,406] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:08,420] {logging_mixin.py:115} INFO - [2024-01-17 01:04:08,419] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:04:08,421] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:08,440] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.043 seconds
[2024-01-17 01:04:18,524] {processor.py:153} INFO - Started process (PID=181) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:18,525] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:04:18,526] {logging_mixin.py:115} INFO - [2024-01-17 01:04:18,526] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:18,537] {logging_mixin.py:115} INFO - [2024-01-17 01:04:18,536] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:04:18,538] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:18,560] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.040 seconds
[2024-01-17 01:04:28,664] {processor.py:153} INFO - Started process (PID=186) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:28,665] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:04:28,666] {logging_mixin.py:115} INFO - [2024-01-17 01:04:28,666] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:28,674] {logging_mixin.py:115} INFO - [2024-01-17 01:04:28,672] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:04:28,674] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:28,700] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.039 seconds
[2024-01-17 01:04:38,819] {processor.py:153} INFO - Started process (PID=191) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:38,821] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:04:38,822] {logging_mixin.py:115} INFO - [2024-01-17 01:04:38,822] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:38,834] {logging_mixin.py:115} INFO - [2024-01-17 01:04:38,832] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:04:38,834] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:38,854] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.039 seconds
[2024-01-17 01:04:48,934] {processor.py:153} INFO - Started process (PID=196) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:48,935] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:04:48,936] {logging_mixin.py:115} INFO - [2024-01-17 01:04:48,936] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:48,944] {logging_mixin.py:115} INFO - [2024-01-17 01:04:48,942] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:04:48,944] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:48,962] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.031 seconds
[2024-01-17 01:04:59,001] {processor.py:153} INFO - Started process (PID=201) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:59,002] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:04:59,003] {logging_mixin.py:115} INFO - [2024-01-17 01:04:59,003] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:59,011] {logging_mixin.py:115} INFO - [2024-01-17 01:04:59,010] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:04:59,012] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:04:59,031] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.033 seconds
[2024-01-17 01:05:09,128] {processor.py:153} INFO - Started process (PID=206) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:09,130] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:05:09,131] {logging_mixin.py:115} INFO - [2024-01-17 01:05:09,131] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:09,142] {logging_mixin.py:115} INFO - [2024-01-17 01:05:09,140] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:05:09,143] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:09,161] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.037 seconds
[2024-01-17 01:05:19,216] {processor.py:153} INFO - Started process (PID=211) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:19,219] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:05:19,220] {logging_mixin.py:115} INFO - [2024-01-17 01:05:19,220] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:19,231] {logging_mixin.py:115} INFO - [2024-01-17 01:05:19,230] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:05:19,232] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:19,255] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.043 seconds
[2024-01-17 01:05:29,310] {processor.py:153} INFO - Started process (PID=216) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:29,312] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:05:29,313] {logging_mixin.py:115} INFO - [2024-01-17 01:05:29,313] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:29,323] {logging_mixin.py:115} INFO - [2024-01-17 01:05:29,321] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:05:29,324] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:29,348] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.040 seconds
[2024-01-17 01:05:39,410] {processor.py:153} INFO - Started process (PID=221) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:39,411] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:05:39,412] {logging_mixin.py:115} INFO - [2024-01-17 01:05:39,412] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:39,424] {logging_mixin.py:115} INFO - [2024-01-17 01:05:39,422] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:05:39,425] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:39,446] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.041 seconds
[2024-01-17 01:05:49,553] {processor.py:153} INFO - Started process (PID=226) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:49,557] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:05:49,559] {logging_mixin.py:115} INFO - [2024-01-17 01:05:49,559] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:49,571] {logging_mixin.py:115} INFO - [2024-01-17 01:05:49,569] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:05:49,572] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:49,592] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.044 seconds
[2024-01-17 01:05:59,639] {processor.py:153} INFO - Started process (PID=231) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:59,642] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:05:59,643] {logging_mixin.py:115} INFO - [2024-01-17 01:05:59,643] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:59,653] {logging_mixin.py:115} INFO - [2024-01-17 01:05:59,652] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:05:59,654] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:05:59,673] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.038 seconds
[2024-01-17 01:06:09,744] {processor.py:153} INFO - Started process (PID=236) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:06:09,747] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:06:09,749] {logging_mixin.py:115} INFO - [2024-01-17 01:06:09,749] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:06:09,761] {logging_mixin.py:115} INFO - [2024-01-17 01:06:09,760] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:06:09,762] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:06:09,782] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.044 seconds
[2024-01-17 01:06:19,868] {processor.py:153} INFO - Started process (PID=241) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:06:19,871] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:06:19,872] {logging_mixin.py:115} INFO - [2024-01-17 01:06:19,872] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:06:19,882] {logging_mixin.py:115} INFO - [2024-01-17 01:06:19,880] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:06:19,882] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:06:19,903] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.039 seconds
[2024-01-17 01:06:29,963] {processor.py:153} INFO - Started process (PID=246) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:06:29,964] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:06:29,966] {logging_mixin.py:115} INFO - [2024-01-17 01:06:29,966] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:06:29,976] {logging_mixin.py:115} INFO - [2024-01-17 01:06:29,975] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:06:29,977] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:06:29,996] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.038 seconds
[2024-01-17 01:06:40,039] {processor.py:153} INFO - Started process (PID=251) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:06:40,040] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:06:40,042] {logging_mixin.py:115} INFO - [2024-01-17 01:06:40,042] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:06:40,053] {logging_mixin.py:115} INFO - [2024-01-17 01:06:40,051] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:06:40,054] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:06:40,077] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.041 seconds
[2024-01-17 01:06:50,152] {processor.py:153} INFO - Started process (PID=256) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:06:50,154] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:06:50,155] {logging_mixin.py:115} INFO - [2024-01-17 01:06:50,155] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:06:50,163] {logging_mixin.py:115} INFO - [2024-01-17 01:06:50,162] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:06:50,164] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:06:50,183] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.034 seconds
[2024-01-17 01:07:00,269] {processor.py:153} INFO - Started process (PID=261) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:00,271] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:07:00,272] {logging_mixin.py:115} INFO - [2024-01-17 01:07:00,272] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:00,283] {logging_mixin.py:115} INFO - [2024-01-17 01:07:00,282] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:07:00,284] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:00,302] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.037 seconds
[2024-01-17 01:07:10,391] {processor.py:153} INFO - Started process (PID=266) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:10,394] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:07:10,395] {logging_mixin.py:115} INFO - [2024-01-17 01:07:10,395] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:10,406] {logging_mixin.py:115} INFO - [2024-01-17 01:07:10,405] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:07:10,408] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:10,426] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.039 seconds
[2024-01-17 01:07:20,459] {processor.py:153} INFO - Started process (PID=271) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:20,460] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:07:20,461] {logging_mixin.py:115} INFO - [2024-01-17 01:07:20,461] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:20,468] {logging_mixin.py:115} INFO - [2024-01-17 01:07:20,467] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:07:20,469] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:20,487] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.031 seconds
[2024-01-17 01:07:30,562] {processor.py:153} INFO - Started process (PID=276) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:30,563] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:07:30,564] {logging_mixin.py:115} INFO - [2024-01-17 01:07:30,564] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:30,574] {logging_mixin.py:115} INFO - [2024-01-17 01:07:30,572] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:07:30,574] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:30,597] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.038 seconds
[2024-01-17 01:07:40,677] {processor.py:153} INFO - Started process (PID=281) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:40,679] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:07:40,680] {logging_mixin.py:115} INFO - [2024-01-17 01:07:40,680] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:40,693] {logging_mixin.py:115} INFO - [2024-01-17 01:07:40,691] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:07:40,694] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:40,714] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.043 seconds
[2024-01-17 01:07:50,774] {processor.py:153} INFO - Started process (PID=286) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:50,776] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:07:50,777] {logging_mixin.py:115} INFO - [2024-01-17 01:07:50,777] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:50,792] {logging_mixin.py:115} INFO - [2024-01-17 01:07:50,789] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:07:50,793] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:07:50,815] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.046 seconds
[2024-01-17 01:08:00,879] {processor.py:153} INFO - Started process (PID=291) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:00,881] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:08:00,882] {logging_mixin.py:115} INFO - [2024-01-17 01:08:00,882] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:00,892] {logging_mixin.py:115} INFO - [2024-01-17 01:08:00,890] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:08:00,893] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:00,918] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.042 seconds
[2024-01-17 01:08:11,027] {processor.py:153} INFO - Started process (PID=296) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:11,028] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:08:11,029] {logging_mixin.py:115} INFO - [2024-01-17 01:08:11,029] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:11,039] {logging_mixin.py:115} INFO - [2024-01-17 01:08:11,038] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:08:11,040] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:11,065] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.041 seconds
[2024-01-17 01:08:21,128] {processor.py:153} INFO - Started process (PID=301) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:21,129] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:08:21,130] {logging_mixin.py:115} INFO - [2024-01-17 01:08:21,130] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:21,136] {logging_mixin.py:115} INFO - [2024-01-17 01:08:21,135] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:08:21,137] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:21,154] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.029 seconds
[2024-01-17 01:08:31,200] {processor.py:153} INFO - Started process (PID=306) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:31,202] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:08:31,203] {logging_mixin.py:115} INFO - [2024-01-17 01:08:31,203] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:31,215] {logging_mixin.py:115} INFO - [2024-01-17 01:08:31,213] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:08:31,216] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:31,238] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.043 seconds
[2024-01-17 01:08:41,311] {processor.py:153} INFO - Started process (PID=311) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:41,313] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:08:41,314] {logging_mixin.py:115} INFO - [2024-01-17 01:08:41,314] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:41,326] {logging_mixin.py:115} INFO - [2024-01-17 01:08:41,324] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:08:41,327] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:41,346] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.039 seconds
[2024-01-17 01:08:51,415] {processor.py:153} INFO - Started process (PID=316) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:51,417] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:08:51,418] {logging_mixin.py:115} INFO - [2024-01-17 01:08:51,418] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:51,426] {logging_mixin.py:115} INFO - [2024-01-17 01:08:51,425] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:08:51,426] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:08:51,445] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.032 seconds
[2024-01-17 01:09:01,556] {processor.py:153} INFO - Started process (PID=321) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:01,558] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:09:01,559] {logging_mixin.py:115} INFO - [2024-01-17 01:09:01,559] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:01,568] {logging_mixin.py:115} INFO - [2024-01-17 01:09:01,567] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:09:01,569] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:01,589] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.035 seconds
[2024-01-17 01:09:11,648] {processor.py:153} INFO - Started process (PID=326) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:11,651] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:09:11,652] {logging_mixin.py:115} INFO - [2024-01-17 01:09:11,652] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:11,663] {logging_mixin.py:115} INFO - [2024-01-17 01:09:11,662] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:09:11,664] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:11,685] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.041 seconds
[2024-01-17 01:09:21,757] {processor.py:153} INFO - Started process (PID=331) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:21,758] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:09:21,760] {logging_mixin.py:115} INFO - [2024-01-17 01:09:21,759] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:21,769] {logging_mixin.py:115} INFO - [2024-01-17 01:09:21,767] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:09:21,769] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:21,788] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.034 seconds
[2024-01-17 01:09:31,838] {processor.py:153} INFO - Started process (PID=336) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:31,840] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:09:31,841] {logging_mixin.py:115} INFO - [2024-01-17 01:09:31,841] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:31,849] {logging_mixin.py:115} INFO - [2024-01-17 01:09:31,848] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:09:31,850] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:31,867] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.031 seconds
[2024-01-17 01:09:41,934] {processor.py:153} INFO - Started process (PID=341) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:41,936] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:09:41,939] {logging_mixin.py:115} INFO - [2024-01-17 01:09:41,939] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:41,948] {logging_mixin.py:115} INFO - [2024-01-17 01:09:41,947] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:09:41,949] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:41,968] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.040 seconds
[2024-01-17 01:09:52,061] {processor.py:153} INFO - Started process (PID=346) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:52,064] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:09:52,067] {logging_mixin.py:115} INFO - [2024-01-17 01:09:52,067] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:52,079] {logging_mixin.py:115} INFO - [2024-01-17 01:09:52,078] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:09:52,081] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:09:52,100] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.046 seconds
[2024-01-17 01:10:02,141] {processor.py:153} INFO - Started process (PID=351) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:02,142] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:10:02,144] {logging_mixin.py:115} INFO - [2024-01-17 01:10:02,144] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:02,150] {logging_mixin.py:115} INFO - [2024-01-17 01:10:02,149] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:10:02,151] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:02,168] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.029 seconds
[2024-01-17 01:10:12,238] {processor.py:153} INFO - Started process (PID=356) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:12,238] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:10:12,240] {logging_mixin.py:115} INFO - [2024-01-17 01:10:12,240] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:12,248] {logging_mixin.py:115} INFO - [2024-01-17 01:10:12,247] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:10:12,249] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:12,271] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.036 seconds
[2024-01-17 01:10:22,309] {processor.py:153} INFO - Started process (PID=361) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:22,310] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:10:22,311] {logging_mixin.py:115} INFO - [2024-01-17 01:10:22,311] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:22,318] {logging_mixin.py:115} INFO - [2024-01-17 01:10:22,317] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:10:22,319] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:22,336] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.029 seconds
[2024-01-17 01:10:32,406] {processor.py:153} INFO - Started process (PID=366) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:32,407] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:10:32,409] {logging_mixin.py:115} INFO - [2024-01-17 01:10:32,409] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:32,417] {logging_mixin.py:115} INFO - [2024-01-17 01:10:32,416] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:10:32,418] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:32,438] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.036 seconds
[2024-01-17 01:10:42,515] {processor.py:153} INFO - Started process (PID=371) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:42,518] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:10:42,520] {logging_mixin.py:115} INFO - [2024-01-17 01:10:42,520] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:42,534] {logging_mixin.py:115} INFO - [2024-01-17 01:10:42,530] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:10:42,537] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:42,557] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.046 seconds
[2024-01-17 01:10:52,596] {processor.py:153} INFO - Started process (PID=376) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:52,598] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:10:52,599] {logging_mixin.py:115} INFO - [2024-01-17 01:10:52,599] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:52,606] {logging_mixin.py:115} INFO - [2024-01-17 01:10:52,605] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:10:52,607] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:10:52,624] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.032 seconds
[2024-01-17 01:11:02,741] {processor.py:153} INFO - Started process (PID=381) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:02,742] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:11:02,744] {logging_mixin.py:115} INFO - [2024-01-17 01:11:02,744] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:02,752] {logging_mixin.py:115} INFO - [2024-01-17 01:11:02,751] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:11:02,753] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:02,773] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.035 seconds
[2024-01-17 01:11:12,827] {processor.py:153} INFO - Started process (PID=386) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:12,829] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:11:12,831] {logging_mixin.py:115} INFO - [2024-01-17 01:11:12,831] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:12,841] {logging_mixin.py:115} INFO - [2024-01-17 01:11:12,840] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:11:12,842] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:12,863] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.040 seconds
[2024-01-17 01:11:22,931] {processor.py:153} INFO - Started process (PID=391) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:22,932] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:11:22,934] {logging_mixin.py:115} INFO - [2024-01-17 01:11:22,934] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:22,946] {logging_mixin.py:115} INFO - [2024-01-17 01:11:22,944] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:11:22,947] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:22,967] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.041 seconds
[2024-01-17 01:11:33,025] {processor.py:153} INFO - Started process (PID=396) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:33,027] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:11:33,029] {logging_mixin.py:115} INFO - [2024-01-17 01:11:33,029] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:33,040] {logging_mixin.py:115} INFO - [2024-01-17 01:11:33,039] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:11:33,041] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:33,060] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.040 seconds
[2024-01-17 01:11:43,165] {processor.py:153} INFO - Started process (PID=401) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:43,167] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:11:43,169] {logging_mixin.py:115} INFO - [2024-01-17 01:11:43,169] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:43,178] {logging_mixin.py:115} INFO - [2024-01-17 01:11:43,177] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:11:43,179] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:43,197] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.036 seconds
[2024-01-17 01:11:53,271] {processor.py:153} INFO - Started process (PID=406) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:53,274] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:11:53,277] {logging_mixin.py:115} INFO - [2024-01-17 01:11:53,276] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:53,286] {logging_mixin.py:115} INFO - [2024-01-17 01:11:53,285] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:11:53,287] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:11:53,306] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.040 seconds
[2024-01-17 01:12:03,384] {processor.py:153} INFO - Started process (PID=411) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:03,385] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:12:03,387] {logging_mixin.py:115} INFO - [2024-01-17 01:12:03,387] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:03,396] {logging_mixin.py:115} INFO - [2024-01-17 01:12:03,394] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:12:03,397] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:03,415] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.035 seconds
[2024-01-17 01:12:13,490] {processor.py:153} INFO - Started process (PID=416) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:13,491] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:12:13,492] {logging_mixin.py:115} INFO - [2024-01-17 01:12:13,492] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:13,501] {logging_mixin.py:115} INFO - [2024-01-17 01:12:13,499] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:12:13,501] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:13,519] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.034 seconds
[2024-01-17 01:12:23,580] {processor.py:153} INFO - Started process (PID=421) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:23,582] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:12:23,585] {logging_mixin.py:115} INFO - [2024-01-17 01:12:23,584] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:23,597] {logging_mixin.py:115} INFO - [2024-01-17 01:12:23,596] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 4, in <module>
    from scriptCrypto import get_crypto_data
ModuleNotFoundError: No module named 'scriptCrypto'
[2024-01-17 01:12:23,599] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:23,619] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.043 seconds
[2024-01-17 01:12:25,611] {processor.py:153} INFO - Started process (PID=426) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:25,613] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:12:25,614] {logging_mixin.py:115} INFO - [2024-01-17 01:12:25,614] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:25,622] {logging_mixin.py:115} INFO - [2024-01-17 01:12:25,621] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 1, in <module>
    sys.path.insert(0, abspath(dirname(dirname(__file__))))
NameError: name 'sys' is not defined
[2024-01-17 01:12:25,623] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:25,640] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.032 seconds
[2024-01-17 01:12:45,520] {processor.py:153} INFO - Started process (PID=170) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:45,521] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:12:45,521] {logging_mixin.py:115} INFO - [2024-01-17 01:12:45,521] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:45,525] {logging_mixin.py:115} INFO - [2024-01-17 01:12:45,524] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 1, in <module>
    sys.path.insert(0, abspath(dirname(dirname(__file__))))
NameError: name 'sys' is not defined
[2024-01-17 01:12:45,525] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:45,543] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.026 seconds
[2024-01-17 01:12:55,589] {processor.py:153} INFO - Started process (PID=175) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:55,590] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:12:55,591] {logging_mixin.py:115} INFO - [2024-01-17 01:12:55,591] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:55,596] {logging_mixin.py:115} INFO - [2024-01-17 01:12:55,595] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 1, in <module>
    sys.path.insert(0, abspath(dirname(dirname(__file__))))
NameError: name 'sys' is not defined
[2024-01-17 01:12:55,597] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:12:55,618] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.034 seconds
[2024-01-17 01:13:05,664] {processor.py:153} INFO - Started process (PID=180) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:05,666] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:13:05,666] {logging_mixin.py:115} INFO - [2024-01-17 01:13:05,666] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:05,670] {logging_mixin.py:115} INFO - [2024-01-17 01:13:05,669] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 1, in <module>
    sys.path.insert(0, abspath(dirname(dirname(__file__))))
NameError: name 'sys' is not defined
[2024-01-17 01:13:05,671] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:05,691] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.029 seconds
[2024-01-17 01:13:15,736] {processor.py:153} INFO - Started process (PID=185) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:15,737] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:13:15,742] {logging_mixin.py:115} INFO - [2024-01-17 01:13:15,741] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:15,746] {logging_mixin.py:115} INFO - [2024-01-17 01:13:15,745] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 1, in <module>
    sys.path.insert(0, abspath(dirname(dirname(__file__))))
NameError: name 'sys' is not defined
[2024-01-17 01:13:15,747] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:15,766] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.033 seconds
[2024-01-17 01:13:25,811] {processor.py:153} INFO - Started process (PID=190) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:25,812] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:13:25,813] {logging_mixin.py:115} INFO - [2024-01-17 01:13:25,813] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:25,817] {logging_mixin.py:115} INFO - [2024-01-17 01:13:25,816] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 1, in <module>
    sys.path.insert(0, abspath(dirname(dirname(__file__))))
NameError: name 'sys' is not defined
[2024-01-17 01:13:25,818] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:25,835] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.028 seconds
[2024-01-17 01:13:35,906] {processor.py:153} INFO - Started process (PID=195) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:35,915] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:13:35,916] {logging_mixin.py:115} INFO - [2024-01-17 01:13:35,916] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:35,920] {logging_mixin.py:115} INFO - [2024-01-17 01:13:35,919] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 1, in <module>
    sys.path.insert(0, abspath(dirname(dirname(__file__))))
NameError: name 'sys' is not defined
[2024-01-17 01:13:35,920] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:35,938] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.035 seconds
[2024-01-17 01:13:46,016] {processor.py:153} INFO - Started process (PID=200) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:46,018] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:13:46,020] {logging_mixin.py:115} INFO - [2024-01-17 01:13:46,019] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:46,025] {logging_mixin.py:115} INFO - [2024-01-17 01:13:46,023] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 1, in <module>
    sys.path.insert(0, abspath(dirname(dirname(__file__))))
NameError: name 'sys' is not defined
[2024-01-17 01:13:46,025] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:46,044] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.032 seconds
[2024-01-17 01:13:56,133] {processor.py:153} INFO - Started process (PID=205) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:56,136] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:13:56,138] {logging_mixin.py:115} INFO - [2024-01-17 01:13:56,138] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:56,145] {logging_mixin.py:115} INFO - [2024-01-17 01:13:56,143] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 1, in <module>
    sys.path.insert(0, abspath(dirname(dirname(__file__))))
NameError: name 'sys' is not defined
[2024-01-17 01:13:56,146] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:13:56,167] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.039 seconds
[2024-01-17 01:14:06,233] {processor.py:153} INFO - Started process (PID=210) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:14:06,234] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:14:06,236] {logging_mixin.py:115} INFO - [2024-01-17 01:14:06,235] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:14:06,241] {logging_mixin.py:115} INFO - [2024-01-17 01:14:06,240] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 1, in <module>
    sys.path.insert(0, abspath(dirname(dirname(__file__))))
NameError: name 'sys' is not defined
[2024-01-17 01:14:06,242] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:14:06,266] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.037 seconds
[2024-01-17 01:14:16,323] {processor.py:153} INFO - Started process (PID=215) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:14:16,325] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:14:16,326] {logging_mixin.py:115} INFO - [2024-01-17 01:14:16,326] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:14:16,335] {logging_mixin.py:115} INFO - [2024-01-17 01:14:16,332] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 1, in <module>
    sys.path.insert(0, abspath(dirname(dirname(__file__))))
NameError: name 'sys' is not defined
[2024-01-17 01:14:16,337] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:14:16,365] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.047 seconds
[2024-01-17 01:14:26,442] {processor.py:153} INFO - Started process (PID=220) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:14:26,445] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:14:26,446] {logging_mixin.py:115} INFO - [2024-01-17 01:14:26,446] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:14:26,452] {logging_mixin.py:115} INFO - [2024-01-17 01:14:26,450] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 1, in <module>
    sys.path.insert(0, abspath(dirname(dirname(__file__))))
NameError: name 'sys' is not defined
[2024-01-17 01:14:26,453] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:14:26,473] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.037 seconds
[2024-01-17 01:14:34,510] {processor.py:153} INFO - Started process (PID=225) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:14:34,512] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:14:34,514] {logging_mixin.py:115} INFO - [2024-01-17 01:14:34,514] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:14:34,538] {logging_mixin.py:115} INFO - [2024-01-17 01:14:34,536] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 6, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:14:34,539] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:14:34,561] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.057 seconds
[2024-01-17 01:19:13,918] {processor.py:153} INFO - Started process (PID=170) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:19:13,919] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:19:13,920] {logging_mixin.py:115} INFO - [2024-01-17 01:19:13,920] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:19:13,929] {logging_mixin.py:115} INFO - [2024-01-17 01:19:13,927] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:19:13,930] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:19:13,955] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.041 seconds
[2024-01-17 01:19:24,019] {processor.py:153} INFO - Started process (PID=175) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:19:24,020] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:19:24,021] {logging_mixin.py:115} INFO - [2024-01-17 01:19:24,021] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:19:24,028] {logging_mixin.py:115} INFO - [2024-01-17 01:19:24,026] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:19:24,028] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:19:24,047] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.034 seconds
[2024-01-17 01:19:34,140] {processor.py:153} INFO - Started process (PID=180) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:19:34,142] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:19:34,144] {logging_mixin.py:115} INFO - [2024-01-17 01:19:34,144] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:19:34,154] {logging_mixin.py:115} INFO - [2024-01-17 01:19:34,152] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:19:34,155] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:19:34,175] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.040 seconds
[2024-01-17 01:19:44,204] {processor.py:153} INFO - Started process (PID=185) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:19:44,206] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:19:44,208] {logging_mixin.py:115} INFO - [2024-01-17 01:19:44,208] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:19:44,213] {logging_mixin.py:115} INFO - [2024-01-17 01:19:44,211] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:19:44,214] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:19:44,235] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.034 seconds
[2024-01-17 01:19:54,305] {processor.py:153} INFO - Started process (PID=190) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:19:54,305] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:19:54,306] {logging_mixin.py:115} INFO - [2024-01-17 01:19:54,306] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:19:54,310] {logging_mixin.py:115} INFO - [2024-01-17 01:19:54,309] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:19:54,311] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:19:54,329] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.027 seconds
[2024-01-17 01:20:04,406] {processor.py:153} INFO - Started process (PID=195) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:04,409] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:20:04,411] {logging_mixin.py:115} INFO - [2024-01-17 01:20:04,410] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:04,417] {logging_mixin.py:115} INFO - [2024-01-17 01:20:04,415] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:20:04,418] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:04,437] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.035 seconds
[2024-01-17 01:20:14,494] {processor.py:153} INFO - Started process (PID=200) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:14,496] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:20:14,497] {logging_mixin.py:115} INFO - [2024-01-17 01:20:14,496] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:14,501] {logging_mixin.py:115} INFO - [2024-01-17 01:20:14,500] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:20:14,502] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:14,520] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.030 seconds
[2024-01-17 01:20:24,598] {processor.py:153} INFO - Started process (PID=205) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:24,600] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:20:24,601] {logging_mixin.py:115} INFO - [2024-01-17 01:20:24,601] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:24,607] {logging_mixin.py:115} INFO - [2024-01-17 01:20:24,606] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:20:24,608] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:24,628] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.034 seconds
[2024-01-17 01:20:34,718] {processor.py:153} INFO - Started process (PID=210) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:34,719] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:20:34,721] {logging_mixin.py:115} INFO - [2024-01-17 01:20:34,721] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:34,728] {logging_mixin.py:115} INFO - [2024-01-17 01:20:34,726] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:20:34,728] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:34,749] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.035 seconds
[2024-01-17 01:20:44,802] {processor.py:153} INFO - Started process (PID=215) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:44,804] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:20:44,805] {logging_mixin.py:115} INFO - [2024-01-17 01:20:44,805] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:44,809] {logging_mixin.py:115} INFO - [2024-01-17 01:20:44,808] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:20:44,810] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:44,831] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.032 seconds
[2024-01-17 01:20:54,917] {processor.py:153} INFO - Started process (PID=220) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:54,921] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:20:54,922] {logging_mixin.py:115} INFO - [2024-01-17 01:20:54,922] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:54,927] {logging_mixin.py:115} INFO - [2024-01-17 01:20:54,926] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:20:54,928] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:20:54,948] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.036 seconds
[2024-01-17 01:21:05,025] {processor.py:153} INFO - Started process (PID=225) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:05,028] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:21:05,029] {logging_mixin.py:115} INFO - [2024-01-17 01:21:05,029] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:05,036] {logging_mixin.py:115} INFO - [2024-01-17 01:21:05,033] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:21:05,037] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:05,060] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.038 seconds
[2024-01-17 01:21:15,137] {processor.py:153} INFO - Started process (PID=230) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:15,139] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:21:15,141] {logging_mixin.py:115} INFO - [2024-01-17 01:21:15,140] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:15,146] {logging_mixin.py:115} INFO - [2024-01-17 01:21:15,145] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:21:15,147] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:15,167] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.033 seconds
[2024-01-17 01:21:25,234] {processor.py:153} INFO - Started process (PID=235) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:25,237] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:21:25,238] {logging_mixin.py:115} INFO - [2024-01-17 01:21:25,238] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:25,245] {logging_mixin.py:115} INFO - [2024-01-17 01:21:25,244] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:21:25,247] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:25,266] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.036 seconds
[2024-01-17 01:21:35,322] {processor.py:153} INFO - Started process (PID=240) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:35,325] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:21:35,326] {logging_mixin.py:115} INFO - [2024-01-17 01:21:35,326] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:35,333] {logging_mixin.py:115} INFO - [2024-01-17 01:21:35,331] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:21:35,334] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:35,356] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.037 seconds
[2024-01-17 01:21:45,439] {processor.py:153} INFO - Started process (PID=245) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:45,440] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:21:45,442] {logging_mixin.py:115} INFO - [2024-01-17 01:21:45,442] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:45,447] {logging_mixin.py:115} INFO - [2024-01-17 01:21:45,446] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:21:45,448] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:45,468] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.033 seconds
[2024-01-17 01:21:55,517] {processor.py:153} INFO - Started process (PID=250) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:55,520] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:21:55,522] {logging_mixin.py:115} INFO - [2024-01-17 01:21:55,521] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:55,528] {logging_mixin.py:115} INFO - [2024-01-17 01:21:55,527] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:21:55,530] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:21:55,550] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.038 seconds
[2024-01-17 01:22:05,623] {processor.py:153} INFO - Started process (PID=255) to work on /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:22:05,625] {processor.py:641} INFO - Processing file /opt/airflow/dags/dagCrypto.py for tasks to queue
[2024-01-17 01:22:05,627] {logging_mixin.py:115} INFO - [2024-01-17 01:22:05,626] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:22:05,634] {logging_mixin.py:115} INFO - [2024-01-17 01:22:05,632] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dagCrypto.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagCrypto.py", line 3, in <module>
    from ..scriptCrypto.py import get_crypto_data
ImportError: attempted relative import with no known parent package
[2024-01-17 01:22:05,634] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dagCrypto.py
[2024-01-17 01:22:05,656] {processor.py:161} INFO - Processing /opt/airflow/dags/dagCrypto.py took 0.037 seconds
